[general]
import = [
  "~/.config/alacritty/catppuccin-macchiato.toml",
  "~/.config/alacritty/private.toml",
]

[terminal.shell]
program = "/bin/zsh"
args = ["-l", "-c", "tmux attach -t 'λ' || tmux new -s 'λ'"]

[window]
dimensions = { columns = 200, lines = 60 }
dynamic_title = true
resize_increments = true
decorations = "Buttonless"
padding = { x = 12, y = 12 }
option_as_alt = "Both"

[keyboard]
bindings = [
  { key = "Left", mods = "Command|Option", chars = "\u001B[1;5D" },  # ctrl+left
  { key = "Right", mods = "Command|Option", chars = "\u001B[1;5C" }, # ctrl+right
  { key = "Left", mods = "Command|Shift", chars = "\u001B[1;6D" },   # ctrl+shift+left
  { key = "Right", mods = "Command|Shift", chars = "\u001B[1;6C" },  # ctrl+shift+right
  { key = "Up", mods = "Command|Shift", chars = "\u0001K" },         # ctrl+a K
  { key = "Down", mods = "Command|Shift", chars = "\u0001k" },       # ctrl+a k
  { key = "h", mods = "Command|Option", chars = "\u001B[1;5D" },     # ctrl+left
  { key = "l", mods = "Command|Option", chars = "\u001B[1;5C" },     # ctrl+right
  { key = "h", mods = "Command|Shift", chars = "\u001B[1;6D" },      # ctrl+shift+left
  { key = "l", mods = "Command|Shift", chars = "\u001B[1;6C" },      # ctrl+shift+right
  { key = "k", mods = "Command|Shift", chars = "\u0001K" },          # ctrl+a K
  { key = "j", mods = "Command|Shift", chars = "\u0001k" },          # ctrl+a k
  { key = "T", mods = "Command", chars = "\u0001c" },                # ctrl+a c
  { key = "W", mods = "Command", chars = "\u0001x" },                # ctrl+a x
  { key = "D", mods = "Command", chars = "\u0001|" },                # ctrl+a |
  { key = "D", mods = "Command|Shift", chars = "\u0001-" },          # ctrl+a -
  { key = "F", mods = "Command", chars = "\u0001\\" },               # ctrl+a \
  { key = "K", mods = "Command", chars = "\u000b" },                 # ctrl+k
  { key = "L", mods = "Command", chars = "\u0001;" },                # ctrl+a ;
  { key = ",", mods = "Command", chars = "\u0001L" },                # ctrl+a L  (jump to last session)
  { key = 36, mods = "Command", action = "ToggleFullscreen" },       # toggle fullscreen
  { key = "Return", mods = "Command|Shift", chars = "\u0001z" },     # ctrl+a z
  { key = "s", mods = "Command", chars = "\u0001s" },                # ctrl+a s  (view tmux sessions)
  { key = "p", mods = "Command", chars = "\u0001F" },                # ctrl+a F  (open tmux-sessionizer)
  { key = "Right", mods = "Alt", chars = "\u001BF" },                # jump right by a word
  { key = "Left", mods = "Alt", chars = "\u001BB" },                 # jump left by a word
  { key = "Left", mods = "Command", chars = "\u001b[H" },            # jump to start of line
  { key = "Right", mods = "Command", chars = "\u001b[F" },           # jump to end of line
  { key = "Back", mods = "Command", chars = "\u0015" },              # delete to start of line
  { key = "3", mods = "Option", chars = "#" },                       # This would be overriden otherwise by option_as_alt
]

[mouse]
hide_when_typing = true

[[hints.enabled]]
binding = { key = "u", mods = "Control|Shift" }
command = "open"
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true

[[hints.enabled]]
binding = { key = "i", mods = "Control|Shift" }
command = { program = "sh", args = ["-c", "printf ${0#./} | pbcopy"] }
regex = "\\./[^\\s:]+:\\d+"
hyperlinks = false
post_processing = false
persist = false
mouse.enabled = true

[font]
size = 12
offset = { x = 1, y = 1 }
bold = { family = "JetBrainsMono Nerd Font" }
italic = { family = "JetBrainsMono Nerd Font" }
normal = { family = "JetBrainsMono Nerd Font" }
