import = [
  "~/.config/alacritty/catppuccin-macchiato.toml",
  "~/.config/alacritty/private.toml",
]

[shell]
program = "/bin/zsh"
args = ["-l", "-c", "tmux attach -t 'λ' || tmux new -s 'λ'"]

[window]
dimensions = { columns = 200, lines = 60 }
dynamic_title = true
resize_increments = true
decorations = "None"
padding = { x = 15, y = 15 }

[keyboard]
bindings = [
  { key = "Left", mods = "Command|Option", chars = "\u001B[1;5D" },  # cmd+option+left  -> ctrl+left
  { key = "Right", mods = "Command|Option", chars = "\u001B[1;5C" }, # cmd+option+right -> ctrl+right
  { key = "Left", mods = "Command|Shift", chars = "\u001B[1;6D" },   # cmd+shift+left   -> ctrl+shift+left
  { key = "Right", mods = "Command|Shift", chars = "\u001B[1;6C" },  # cmd+shift+right  -> ctrl+shift+right
  { key = "Up", mods = "Command|Shift", chars = "\u0001K" },         # cmd+shift+up     -> ctrl+a K
  { key = "Down", mods = "Command|Shift", chars = "\u0001k" },       # cmd+shift+down   -> ctrl+a k 
  { key = "T", mods = "Command", chars = "\u0001c" },                # cmd+t            -> ctrl+a c
  { key = "W", mods = "Command", chars = "\u0001x" },                # cmd+w            -> ctrl+a x
  { key = "D", mods = "Command", chars = "\u0001|" },                # cmd+d            -> ctrl+a |
  { key = "D", mods = "Command|Shift", chars = "\u0001-" },          # cmd+shift+d      -> ctrl+a -
  { key = "F", mods = "Command", chars = "\u0001\\" },               # cmd+f            -> ctrl+a \
  { key = "K", mods = "Command", chars = "\u000b" },                 # cmd+k            -> ctrl+k
  { key = "L", mods = "Command", chars = "\u0001;" },                # cmd+L            -> ctrl+a ;
  { key = 36, mods = "Command", action = "ToggleFullscreen" },       # cmd+enter        -> toggle fullscreen
  { key = "Return", mods = "Command|Shift", chars = "\u0001z" },     # cmd+shift+enter  -> ctrl+a z
  { key = "Right", mods = "Alt", chars = "\u001BF" },                # alt+right        -> jump right by a word
  { key = "Left", mods = "Alt", chars = "\u001BB" },                 # alt+left         -> jump left by a word
  { key = "Left", mods = "Command", chars = "\u001b[H" },            # cmd+left         -> jump to start of line
  { key = "Right", mods = "Command", chars = "\u001b[F" },           # cmd+right        -> jump to end of line
  { key = "Back", mods = "Command", chars = "\u0015" },              # cmd+backspace    -> delete to start of line
]

[[hints.enabled]]
binding = { key = "u", mods = "Control|Shift" }
command = "open"
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true

[[hints.enabled]]
binding = { key = "i", mods = "Control|Shift" }
command = { program = "sh", args = ["-c", "printf ${0#./} | pbcopy"] }
regex = "\\./[^\\s:]+:\\d+"
hyperlinks = false
post_processing = false
persist = false
mouse.enabled = true

[font]
size = 13
bold = { family = "DejaVuSansM Nerd Font Mono" }
italic = { family = "DejaVuSansM Nerd Font Mono" }
normal = { family = "DejaVuSansM Nerd Font Mono" }
