[general]
import = [
  "~/.config/alacritty/catppuccin-macchiato.toml",
  "~/.config/alacritty/private.toml",
]

[terminal.shell]
program = "/bin/zsh"
# args = ["-l", "-c", "zellij attach 'λ' || zellij -s 'λ'"]

[window]
dimensions = { columns = 200, lines = 60 }
dynamic_title = true
resize_increments = true
decorations = "Buttonless"
padding = { x = 12, y = 12 }
option_as_alt = "Both"
opacity = 0.9
blur = true

[colors]
transparent_background_colors = true

[keyboard]
bindings = [
  # Navigate tabs with arrow keys
  { key = "Left", mods = "Command|Option", chars = "\u001b{" },  # alt+{
  { key = "Right", mods = "Command|Option", chars = "\u001b}" }, # alt+}
  # Navigate panes with arrow keys
  { key = "Left", mods = "Command|Shift", chars = "\u001b\u001b[D" },  # alt-left
  { key = "Right", mods = "Command|Shift", chars = "\u001b\u001b[C" }, # alt-right
  { key = "Up", mods = "Command|Shift", chars = "\u001b\u001b[A" },    # alt-up
  { key = "Down", mods = "Command|Shift", chars = "\u001b\u001b[B" },  # alt-down
  # Navigate tabs with h/l
  { key = "h", mods = "Command|Option", chars = "\u001b{" }, # alt+{
  { key = "l", mods = "Command|Option", chars = "\u001b}" }, # alt+}
  # Navigate panes with h/j/k/l
  { key = "h", mods = "Command|Shift", chars = "\u001b\u001b[D" }, # alt-left
  { key = "l", mods = "Command|Shift", chars = "\u001b\u001b[C" }, # alt-right
  { key = "k", mods = "Command|Shift", chars = "\u001b\u001b[A" }, # alt-up
  { key = "j", mods = "Command|Shift", chars = "\u001b\u001b[B" }, # alt-down
  # Open and close tabs/panes
  { key = "T", mods = "Command", chars = "\u001bT" },        # alt-T
  { key = "W", mods = "Command", chars = "\u001bW" },        # alt-W
  { key = "D", mods = "Command", chars = "\u001b%" },        # alt-%
  { key = "D", mods = "Command|Shift", chars = "\u001b\"" }, # alt-"
  # Misc
  # { key = "L", mods = "Command", chars = "\u0001;" },                # ctrl+a ;
  # { key = ",", mods = "Command", chars = "\u0001L" },                # ctrl+a L  (jump to last session)
  { key = "Enter", mods = "Command", action = "ToggleFullscreen" }, # toggle fullscreen
  { key = "Enter", mods = "Command|Shift", chars = "\u001bF" },     # alt-F
  # { key = "p", mods = "Command", chars = "\u0001F" },                # ctrl+a F  (open tmux-sessionizer)
  { key = "3", mods = "Option", chars = "#" }, # This would be overriden otherwise by option_as_alt
]

[mouse]
hide_when_typing = true

[[hints.enabled]]
binding = { key = "u", mods = "Control|Shift" }
command = "open"
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true

[[hints.enabled]]
binding = { key = "i", mods = "Control|Shift" }
command = { program = "sh", args = ["-c", "printf ${0#./} | pbcopy"] }
regex = "\\./[^\\s:]+:\\d+"
hyperlinks = false
post_processing = false
persist = false
mouse.enabled = true

[font]
size = 12
offset = { x = 1, y = 1 }
bold = { family = "JetBrainsMono Nerd Font" }
italic = { family = "JetBrainsMono Nerd Font" }
normal = { family = "JetBrainsMono Nerd Font" }
