[opener]
edit = [
	{ run = "mux-send-keys --close-self \":onc \\\"${@}\\\"\"", block = false },
]
open = [
	{ run = "mux-send-keys --close-self \":onc \\\"${@}\\\"\"", block = false },
]

[manager]
show_hidden = true
