theme = "catppuccin_macchiato_transparent"

[editor]
line-number = "relative"
auto-format = true
bufferline = "always"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.insert]
"C-c" = "normal_mode"

[keys.normal]
C-s = ":w"
C-x = ":buffer-close"
"backspace" = { x = ":buffer-close!" }
A-h = "goto_previous_buffer"
A-l = "goto_next_buffer"
F2 = "rename_symbol"
F10 = ":q"
F12 = "goto_definition"
S-F12 = "goto_reference"

[editor.lsp]
display-messages = true

[editor.indent-guides]
render = true
