theme = "catppuccin_macchiato_transparent"

[editor]
line-number = "relative"
auto-format = true
bufferline = "always"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
display-messages = true

[editor.indent-guides]
render = true

[editor.file-picker]
hidden = false

[keys.select]
X = "select_line_above"
A-x = "extend_to_line_bounds"
p = "paste_clipboard_after"
P = "paste_clipboard_before"
y = "yank_to_clipboard"
R = "replace_selections_with_clipboard"

[keys.normal]
C-s = ":w"
C-x = ":buffer-close"
A-h = "goto_previous_buffer"
A-l = "goto_next_buffer"
F2 = "rename_symbol"
F12 = "goto_definition"
S-F12 = "goto_reference"
X = "select_line_above"
A-x = "extend_to_line_bounds"
p = "paste_clipboard_after"
P = "paste_clipboard_before"
y = "yank_to_clipboard"
R = "replace_selections_with_clipboard"

[keys.normal.backspace]
x = ":buffer-close!"
g = ":reset-diff-change"
a = ":sh tmux popup -d \"#{pane_current_path}\" -xC -yC -w90% -h90% -E lazygit"
s = ":sh tmux popup -d \"#{pane_current_path}\" -xC -yC -w90% -h90% -E yazi"
## Not possible yet until macro keymaps are possible, or if forked
# y = [
#   "select_register",
#   "%",
#   "paste_before",
#   "yank_to_clipboard",
#   "delete_selection",
# ]

[keys.normal.space]
p = "paste_after"
P = "paste_before"
y = "yank"
R = "replace_with_yanked"
