theme = "catppuccin_macchiato_transparent"

[editor]
line-number = "relative"
auto-format = true
bufferline = "always"
end-of-line-diagnostics = "hint"

[editor.lsp]
display-messages = true

[editor.indent-guides]
render = true

[editor.file-picker]
hidden = false

[keys.select] # TODO: this is all duplicated from [keys.normal] - deduplicate
X = "extend_line_above"
A-x = "extend_to_line_bounds"
p = "paste_clipboard_after"
P = "paste_clipboard_before"
y = "yank_to_clipboard"
R = "replace_selections_with_clipboard"
A-up = [ # shift selections up one line
  "ensure_selections_forward",
  "extend_to_line_bounds",
  "extend_char_right",
  "extend_char_left",
  "delete_selection",
  "move_line_up",
  "add_newline_above",
  "move_line_up",
  "replace_with_yanked",
]
A-down = [ # shift selections down one line
  "ensure_selections_forward",
  "extend_to_line_bounds",
  "extend_char_right",
  "extend_char_left",
  "delete_selection",
  "add_newline_below",
  "move_line_down",
  "replace_with_yanked",
]

[keys.normal]
C-s = ":w"
C-x = ":buffer-close"
A-r = ":rla"
A-q = ":q"
A-h = "goto_previous_buffer"
A-l = "goto_next_buffer"
A-S-h = ":buffer-move-left"
A-S-l = ":buffer-move-right"
F2 = "rename_symbol"
F12 = "goto_definition"
S-F12 = "goto_reference"
X = "extend_line_above"
A-x = "extend_to_line_bounds"
A-X = "shrink_to_line_bounds"
p = "paste_clipboard_after"
P = "paste_clipboard_before"
y = "yank_to_clipboard"
R = "replace_selections_with_clipboard"
C-h = "jump_view_left"
C-j = "jump_view_down"
C-k = "jump_view_up"
C-l = "jump_view_right"
F7 = "goto_next_change"
A-F7 = "goto_prev_change"
F8 = "goto_next_diag"
A-F8 = "goto_prev_diag"
A-up = [ # shift selections up one line
  "ensure_selections_forward",
  "extend_to_line_bounds",
  "extend_char_right",
  "extend_char_left",
  "delete_selection",
  "move_line_up",
  "add_newline_above",
  "move_line_up",
  "replace_with_yanked",
]
A-down = [ # shift selections down one line
  "ensure_selections_forward",
  "extend_to_line_bounds",
  "extend_char_right",
  "extend_char_left",
  "delete_selection",
  "add_newline_below",
  "move_line_down",
  "replace_with_yanked",
]

[keys.normal.ret]
x = ":buffer-close!"
g = ":reset-diff-change"
a = ":sh tmux popup -d \"#{pane_current_path}\" -xC -yC -w90% -h90% -E env EDITOR=hx lazygit"
f = ":sh tmux popup -xC -yC -w90% -h90% -E yazi %{filename}"
w = ":sh git blame %{filename} -L %{line_num},%{line_num}"
s = ":sh tmux popup -d \"%{working_dir}\" -xC -yC -w90% -h90% -E env GIT_PAGER='less -+F' git log --follow -p -- %{filename}"
j = "save_selection"
# Jump to first diagnostic on current line (fails on first line but this is rarely required)
d = ["move_line_up", "goto_line_end", "goto_next_diag"]
y = ":sh echo \"%{relative_filename}\" | tr -d '\n' | pbcopy"
Y = ":sh echo \"%{filename}\" | tr -d '\n' | pbcopy"
t = ":toggle inline-diagnostics.cursor-line warning disable"

[keys.normal.space]
p = "paste_after"
P = "paste_before"
y = "yank"
R = "replace_with_yanked"
