theme = "catppuccin_macchiato_transparent"

[editor]
line-number = "relative"
auto-format = true
bufferline = "always"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
C-s = ":w"
C-x = ":buffer-close"
A-h = "goto_previous_buffer"
A-l = "goto_next_buffer"
