theme = "catppuccin_macchiato_transparent"

[editor]
line-number = "relative"
auto-format = true
bufferline = "always"

[editor.lsp]
display-messages = true

[editor.indent-guides]
render = true

[editor.file-picker]
hidden = false

[keys.select]
X = "extend_line_above"
A-x = "extend_to_line_bounds"
p = "paste_clipboard_after"
P = "paste_clipboard_before"
y = "yank_to_clipboard"
R = "replace_selections_with_clipboard"

[keys.normal]
C-s = ":w"
C-x = ":buffer-close"
A-h = "goto_previous_buffer"
A-l = "goto_next_buffer"
F2 = "rename_symbol"
F12 = "goto_definition"
S-F12 = "goto_reference"
X = "extend_line_above"
A-x = "extend_to_line_bounds"
p = "paste_clipboard_after"
P = "paste_clipboard_before"
y = "yank_to_clipboard"
R = "replace_selections_with_clipboard"

[keys.normal.backspace]
x = ":buffer-close!"
g = ":reset-diff-change"
a = ":sh tmux popup -d \"#{pane_current_path}\" -xC -yC -w90% -h90% -E lazygit"
f = ":sh tmux popup -d \"#{pane_current_path}\" -xC -yC -w90% -h90% -E yazi %{filename}"
j = "save_selection"
# Jump to first diagnostic on current line (fails on first line but this is rarely required)
d = ["move_line_up", "goto_line_end", "goto_next_diag"]
## Not possible yet until macro keymaps are possible, or if forked
# y = [
#   "select_register",
#   "%",
#   "paste_before",
#   "yank_to_clipboard",
#   "delete_selection",
# ]

[keys.normal.space]
p = "paste_after"
P = "paste_before"
y = "yank"
R = "replace_with_yanked"
