gui:
  scrollHeight: 10 # how many lines you scroll by
  showFileTree: false # for rendering changes files in a tree format
os:
  edit: 'tmux send-keys -t "$TMUX_PANE" ":onc {{filename}}" Enter'
  editAtLine: 'tmux send-keys -t "$TMUX_PANE" ":onc {{filename}}:{{line}}" Enter'
  editInTerminal: false
