gui:
  scrollHeight: 10 # how many lines you scroll by
  showFileTree: false # for rendering changes files in a tree format
os:
  edit: 'mux-send-keys ":onc {{filename}}"'
  editAtLine: 'mux-send-keys ":onc {{filename}}:{{line}}"'
  editInTerminal: false
