inherits = "catppuccin_macchiato"

"ui.background" = { fg = "foreground" }
"ui.linenr" = { fg = "overlay0" }
"ui.linenr.selected" = { fg = "#e2e8f8" }
"ui.cursor.primary.select" = { fg = "base", bg = "peach" }
"ui.cursor.select" = { fg = "base", bg = "red" }
